# Generated by Django 5.0.6 on 2024-05-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_employee_confirm_password_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
